### ISSUE TITLE
Issue while fetching tradeoff analytics service credentials

### ISSUE THREAD

**Issue by vishwasrao** [IBM-Bluemix/insurance-catalog#11]
Hi,
I tried to install app and run it.
was getting error in logs 
APP/0Error looking up service: [TypeError: Cannot read property 'credentials' of null]Apr 19, 2017 4:02:42 PM
APP/0Error initializing services for /tradeoff: [ReferenceError: tradeoffService is not defined].

It was not able to find credentials.
It worked after changing in app.js
tradeoffService = appEnv.getService("insurance-tradeoff-analytics").credentials;
to 
tradeoffService = appEnv.services.tradeoff_analytics[0];

not sure whether its bug or m missing some configuration.

Thanks,
Vishwas

**Comment by l2fprod** [comment]
@vishwasrao 

Did you deploy using the toolchain?

https://github.com/IBM-Bluemix/logistics-wizard-toolchain

This is the recommended approach as it will deploy all components automatically.

**Comment by vishwasrao** [comment]
I tried deploying standalone application into Bluemix.

Thanks,
Vishwas

**Comment by vishwasrao** [comment]
I tried deploying standalone application into Bluemix.

Thanks,
Vishwas
